### ISSUE TITLE
PS 1.7.x compatibility

### ISSUE THREAD

**Issue by prston** [utrustdev/utrust-for-prestashop#5]
Hello,

PS 1.7.0 was released almost 6 years ago. The module is useless until ported to 1.7.x (there must be not so much stores on 1.6.x...). Is there something on the way or is the compatibility with Prestashop abandoned ?

Thank you.

**Comment by TondaHack** [comment]
Hi @prston,
We're working on the new version of this plugin that supports Prestashop 1.7. 

Please watch the releases so you can get notified once it's out.

![image](https://user-images.githubusercontent.com/8971082/161216359-99f2c208-7151-4d72-af8a-5ce877a631c8.png)

Closing for now.

**Comment by prston** [comment]
Thanks for taking time to answer. Do you have to estimated ETA ?

**Comment by CoOllOokOrion** [comment]
> Hi @prston, We're working on the new version of this plugin that supports Prestashop 1.7.
> 
> Please watch the releases so you can get notified once it's out.
> 
> ![image](https://user-images.githubusercontent.com/8971082/161216359-99f2c208-7151-4d72-af8a-5ce877a631c8.png)
> 
> Closing for now.

Hi @TondaHack 
My developer has finished the compatibility of the Utrust module for prestashop 1.7, now is available for free download for life. You can offer it to your users.
Video demonstration of the module: https://www.berrycast.com/conversations/91224b03-d12b-5b89-982f-1bf75caee4e0
Download link: https://prestashoppe.com/prestashop-modules/34-prestashop-utrust-payment.html
